// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgSSZc0CGGpUkasJUMEccSAvG7T0dpYI8',
    appId: '1:600631183383:web:2ad6d04e338276ccb4b452',
    messagingSenderId: '600631183383',
    projectId: 'gallery-ac534',
    authDomain: 'gallery-ac534.firebaseapp.com',
    storageBucket: 'gallery-ac534.firebasestorage.app',
    measurementId: 'G-YNFFCM0BVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS6i9PFWFjCVg8i3Yy0m2c9B6rugcYw24',
    appId: '1:600631183383:android:ef50b109e9bc5dedb4b452',
    messagingSenderId: '600631183383',
    projectId: 'gallery-ac534',
    storageBucket: 'gallery-ac534.firebasestorage.app',
  );
}
